version: "3"
services:
  node:
    container_name: 'node'
    build:
      context: ..
      dockerfile: ./docker/containers/node/Dockerfile
    volumes:
      - ../:/var/www/src
    tty: true
    ports:
      - 8080:3000
  mysql:
    container_name: 'mysql'
    build:
      context: ..
      dockerfile: ./docker/containers/mysql/Dockerfile
    volumes:
      - ./containers/mysql/db:/var/lib/mysql
#        - ./containers/mysql/my.cnf:/etc/mysql/my.cnf
      - ./containers/mysql/log:/var/log/mysql
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      DB_NAMES: node
      MYSQL_DATABASE: node
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    tty: true
